export const sponsorData = [
    { image: '/c.png' },
    { image: '/cplasplas.png' },
    { image: '/csharp.png' },
    { image: '/csharp.png' },
    { image: '/csharp.png' },
    { image: '/csharp.png' },
    { image: '/csharp.png' },
    { image: '/dj.png' },
    { image: '/java.png' },
    { image: '/php.png' },
    { image: '/python.png' },
    { image: '/swift.png' },
    { image: '/swift.png' },
    { image: '/swift.png' },
    { image: '/swift.png' },
]
