// export const sponsorData = [
//     { image: '/c.png' },
//     { image: '/cplasplas.png' },
//     { image: '/csharp.png' },
//     { image: '/csharp.png' },
//     { image: '/csharp.png' },
//     { image: '/csharp.png' },
//     { image: '/csharp.png' },
//     { image: '/dj.png' },
//     { image: '/java.png' },
//     { image: '/php.png' },
//     { image: '/python.png' },
//     { image: '/swift.png' },
//     { image: '/swift.png' },
//     { image: '/swift.png' },
//     { image: '/swift.png' },
// ]
export const sponsorData = [
    { image: '/apple.svg'},
    { image: '/google.svg'},
    { image: '/Microsoft.svg'},
    { image: '/oracle.svg'},
    { image: '/nextjs-13.svg'},
    { image: '/chatgpt-3.svg'},
    { image: '/react.svg'},
]